global:
  scrape_interval: 1s
  scrape_timeout: 1s
scrape_configs:
- job_name: Universalis Alerts
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:9000
